PAGINATE_USERS_BY = 10
PHONE_NUMBER_VALIDATION_REGEX_VALUE = r'\d{10}'
PHONE_NUMBER_VALIDATION_ERROR_MESSAGE = 'Enter a valid phone number.'

AI_PROFILE_IMAGE_MODEL = 'dall-e-2'
AI_PROFILE_IMAGE_PROMPT = 'small friendly profile picture'
AI_PROFILE_IMAGE_SIZE = '256x256'
AI_PROFILE_IMAGE_REPSONSE_FORMAT = 'b64_json'
